/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.ej01clasificador.gui;

import javax.swing.JOptionPane;

/**
 *
 * @author Alumno
 */
public class ventanaPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ventanaPrincipal.class.getName());
    
    int conDigito = 0;
    int conLetras = 0;
    /**
     * Creates new form ventanaPrincipal
     */
    public ventanaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_clasificar = new javax.swing.JButton();
        lbl_conDigitos = new javax.swing.JLabel();
        lbl_soloLetras = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn_clasificar.setText("Clasificar");
        btn_clasificar.addActionListener(this::btn_clasificarActionPerformed);

        lbl_conDigitos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_conDigitos.setText("Cadenas con digitos: 0");

        lbl_soloLetras.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_soloLetras.setText("Solo letras: 0");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("CLASIFICADOR");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(btn_clasificar)
                    .addComponent(lbl_conDigitos)
                    .addComponent(lbl_soloLetras)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1)
                .addGap(24, 24, 24)
                .addComponent(lbl_soloLetras)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_conDigitos)
                .addGap(18, 18, 18)
                .addComponent(btn_clasificar)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_clasificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clasificarActionPerformed
        String palabra = JOptionPane.showInputDialog(this, "Introduce una palabra", "");
        if(contieneDigito(palabra)){
            conDigito++;
            lbl_conDigitos.setText("Cadenas con digitos: "+conDigito);
        }else if(soloLetras(palabra)){
            conLetras++;
            lbl_soloLetras.setText("Solo letras: "+conLetras);
        }
    }//GEN-LAST:event_btn_clasificarActionPerformed
    
    private boolean contieneDigito(String texto){
        boolean contiene = false;
        for(int i = 0; i< texto.length(); i++){
            if(Character.isDigit(texto.charAt(i))){
                contiene = true;
            }
        }
        return contiene;
    }
    
    private boolean soloLetras(String texto){
        boolean contiene = false;
        for(int i = 0; i<texto.length();i++){
            if(Character.isLetter(texto.charAt(i))){
                contiene = true;
            }
        }
        return contiene;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ventanaPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_clasificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbl_conDigitos;
    private javax.swing.JLabel lbl_soloLetras;
    // End of variables declaration//GEN-END:variables
}
