/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.act07_togglebutton.gui;

import java.awt.Color;

/**
 *
 * @author Alumno
 */
public class ventanaPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ventanaPrincipal.class.getName());

    /**
     * Creates new form ventanaPrincipal
     */
    public ventanaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pan_fondo = new javax.swing.JPanel();
        jtb_interruptor = new javax.swing.JToggleButton();
        lbl_texto = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pan_fondo.setBackground(new java.awt.Color(255, 255, 255));

        jtb_interruptor.setSelected(true);
        jtb_interruptor.setText("OFF");
        jtb_interruptor.addActionListener(this::jtb_interruptorActionPerformed);

        lbl_texto.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_texto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_texto.setText("LUCES ENCENDIDAS");

        javax.swing.GroupLayout pan_fondoLayout = new javax.swing.GroupLayout(pan_fondo);
        pan_fondo.setLayout(pan_fondoLayout);
        pan_fondoLayout.setHorizontalGroup(
            pan_fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pan_fondoLayout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addGroup(pan_fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jtb_interruptor, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_texto))
                .addContainerGap(129, Short.MAX_VALUE))
        );
        pan_fondoLayout.setVerticalGroup(
            pan_fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pan_fondoLayout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(lbl_texto)
                .addGap(47, 47, 47)
                .addComponent(jtb_interruptor)
                .addContainerGap(111, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pan_fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pan_fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtb_interruptorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtb_interruptorActionPerformed
        if(jtb_interruptor.isSelected()){
            pan_fondo.setBackground(Color.white);
            lbl_texto.setForeground(Color.black);
            lbl_texto.setText("LUCES ENCENDIDAS");
            jtb_interruptor.setText("OFF");
        }else{
            pan_fondo.setBackground(Color.black);
            lbl_texto.setForeground(Color.white);
            lbl_texto.setText("LUCES APAGADAS");
            jtb_interruptor.setText("ON");
        }
    }//GEN-LAST:event_jtb_interruptorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ventanaPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton jtb_interruptor;
    private javax.swing.JLabel lbl_texto;
    private javax.swing.JPanel pan_fondo;
    // End of variables declaration//GEN-END:variables
}
