/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.jradiobutton.gui;

/**
 *
 * @author Alumno
 */
public class ventanaPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ventanaPrincipal.class.getName());

    /**
     * Creates new form ventanaPrincipal
     */
    public ventanaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btg_preguntaUno = new javax.swing.ButtonGroup();
        jrb_optA = new javax.swing.JRadioButton();
        jrb_optB = new javax.swing.JRadioButton();
        jrb_optC = new javax.swing.JRadioButton();
        btn_continuar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btg_preguntaUno.add(jrb_optA);
        jrb_optA.setText("Opcion A");
        jrb_optA.addActionListener(this::jrb_optAActionPerformed);

        btg_preguntaUno.add(jrb_optB);
        jrb_optB.setText("Opcion B");

        btg_preguntaUno.add(jrb_optC);
        jrb_optC.setText("Opcion C");

        btn_continuar.setText("Continuar");
        btn_continuar.addActionListener(this::btn_continuarActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(147, 147, 147)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jrb_optA)
                    .addComponent(jrb_optB)
                    .addComponent(jrb_optC)
                    .addComponent(btn_continuar))
                .addContainerGap(170, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jrb_optA)
                .addGap(18, 18, 18)
                .addComponent(jrb_optB)
                .addGap(18, 18, 18)
                .addComponent(jrb_optC)
                .addGap(29, 29, 29)
                .addComponent(btn_continuar)
                .addContainerGap(89, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jrb_optAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrb_optAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrb_optAActionPerformed

    private void btn_continuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_continuarActionPerformed
        if(jrb_optA.isSelected()){
            System.out.println("Opcion A");
        }else if(jrb_optB.isSelected()){
            System.out.println("Opcion B");
        }else if(jrb_optC.isSelected()){
            System.out.println("Opcion C");
        }
        btg_preguntaUno.clearSelection();
    }//GEN-LAST:event_btn_continuarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ventanaPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btg_preguntaUno;
    private javax.swing.JButton btn_continuar;
    private javax.swing.JRadioButton jrb_optA;
    private javax.swing.JRadioButton jrb_optB;
    private javax.swing.JRadioButton jrb_optC;
    // End of variables declaration//GEN-END:variables
}
