/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.act06_combobox.gui;

import java.awt.Color;

/**
 *
 * @author Alumno
 */
public class ventanaPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ventanaPrincipal.class.getName());

    /**
     * Creates new form ventanaPrincipal
     */
    public ventanaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pan_fondo = new javax.swing.JPanel();
        cmb_colorFondo = new javax.swing.JComboBox<>();
        lbl_colorFondo = new javax.swing.JLabel();
        lbl_colorTexto = new javax.swing.JLabel();
        cmb_colorTexto = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pan_fondo.setBackground(new java.awt.Color(51, 204, 0));

        cmb_colorFondo.setMaximumRowCount(5);
        cmb_colorFondo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Verde", "Rojo", "Azul", "Amarillo", "Rosa", "Negro" }));
        cmb_colorFondo.addItemListener(this::cmb_colorFondoItemStateChanged);
        cmb_colorFondo.addActionListener(this::cmb_colorFondoActionPerformed);

        lbl_colorFondo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_colorFondo.setText("Color de fondo:");

        lbl_colorTexto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_colorTexto.setText("Color de Texto:");

        cmb_colorTexto.setMaximumRowCount(3);
        cmb_colorTexto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Blanco", "Negro", "Rojo", "Azul" }));
        cmb_colorTexto.setSelectedIndex(1);
        cmb_colorTexto.addItemListener(this::cmb_colorTextoItemStateChanged);

        javax.swing.GroupLayout pan_fondoLayout = new javax.swing.GroupLayout(pan_fondo);
        pan_fondo.setLayout(pan_fondoLayout);
        pan_fondoLayout.setHorizontalGroup(
            pan_fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pan_fondoLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(pan_fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbl_colorTexto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_colorFondo, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE))
                .addGap(42, 42, 42)
                .addGroup(pan_fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cmb_colorFondo, 0, 103, Short.MAX_VALUE)
                    .addComponent(cmb_colorTexto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(103, Short.MAX_VALUE))
        );
        pan_fondoLayout.setVerticalGroup(
            pan_fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pan_fondoLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(pan_fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmb_colorFondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_colorFondo))
                .addGap(18, 18, 18)
                .addGroup(pan_fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_colorTexto)
                    .addComponent(cmb_colorTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(179, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pan_fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pan_fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmb_colorFondoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmb_colorFondoItemStateChanged
       String seleccionado = (String) cmb_colorFondo.getSelectedItem();
       
       switch(seleccionado){
           case "Verde":
               pan_fondo.setBackground(Color.GREEN);
               break;
           case "Rojo":
               pan_fondo.setBackground(Color.RED);
               break;
           case "Azul":
               pan_fondo.setBackground(Color.BLUE);
               break;
           case "Amarillo":
               pan_fondo.setBackground(Color.YELLOW);
               break;
           case "Rosa":
               pan_fondo.setBackground(Color.PINK);
               break;
           case "Negro":
               pan_fondo.setBackground(Color.BLACK);
               break;
               
       }
    }//GEN-LAST:event_cmb_colorFondoItemStateChanged

    private void cmb_colorFondoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_colorFondoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_colorFondoActionPerformed

    private void cmb_colorTextoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmb_colorTextoItemStateChanged
        int indexSelected = cmb_colorTexto.getSelectedIndex();
        
        switch(indexSelected){
            case 0:
                lbl_colorFondo.setForeground(Color.WHITE);
                lbl_colorTexto.setForeground(Color.white);
                break;
            case 1:
                lbl_colorFondo.setForeground(Color.black);
                lbl_colorTexto.setForeground(Color.black);
                break;
            case 2:
                lbl_colorFondo.setForeground(Color.red);
                lbl_colorTexto.setForeground(Color.red);
                break;
            case 3:
                lbl_colorFondo.setForeground(Color.blue);
                lbl_colorTexto.setForeground(Color.blue);
                break;
                
        }
    }//GEN-LAST:event_cmb_colorTextoItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ventanaPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmb_colorFondo;
    private javax.swing.JComboBox<String> cmb_colorTexto;
    private javax.swing.JLabel lbl_colorFondo;
    private javax.swing.JLabel lbl_colorTexto;
    private javax.swing.JPanel pan_fondo;
    // End of variables declaration//GEN-END:variables
}
